### PR TITLE
Build: FIX: change type for compile

### PR DESCRIPTION
**Pull request by SecH0us3**
The project does not want to compile )

photo_2016-07-06_15-38-11

### CODE REVIEW

**Review by rdzidziguri — APPROVED** [review]

**Comment by ardan-bkennedy** [comment]
@rdzidziguri how did you have rights to do this? Send me an email.  bill@ardanlabs.com

**Comment by ardan-bkennedy** [comment]
@rdzidziguri I want to talk about giving you rights to maintain the code base.

**Comment by AbdalmahmoudIdris** [comment]
Hi guys apparently  @SanSYS solve the problem because currently i have get the project as zip and won't build cause of same things string to byte[]  

kindly @ardan-bkennedy  check

**Comment by TK2017** [comment]
Thanks for the reply @eaba however the file in question from the PR dealt with the concatenation of large messages.

My problem was/is the connection being dropped after some time and transmission stops

**Pull request merged**
